/*
    Copyright (c) 2013 Davorin Šego. All rights reserved.
 */

#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "IIR.h"


/*

  NOTE: Coefficients and filter algorithm generated by FilterDesignLab-IIR

 */


// Elliptic half band filter (halfband-ellip.fdl, Fp 0.38 - Fs 0.50)

IIR* IIR_CreateHalfbandEllip() {

  IIR* self = malloc(sizeof(IIR));
  assert(self != NULL);

  self->numSecondOrderStages = 4;
  self->firstOrderStage      = 1;
  memset(self->w, 0.0, sizeof(self->w));

  self->a[0][0]  = 1.9808391550152610e-01;
  self->a[0][1]  = 1.9808391550152610e-01;
  self->a[1][0]  = 6.7200973465024783e-01;
  self->a[1][1]  =-8.5105686368100508e-02;
  self->a[1][2]  = 6.7200973465024783e-01;
  self->a[2][0]  = 5.1507393617701280e-01;
  self->a[2][1]  = 2.8658616569950921e-02;
  self->a[2][2]  = 5.1507393617701280e-01;
  self->a[3][0]  = 2.8816746504239565e-01;
  self->a[3][1]  = 1.4959559077744328e-01;
  self->a[3][2]  = 2.8816746504239565e-01;
  self->a[4][0]  = 1.0162238957486987e-01;
  self->a[4][1]  = 1.3939473781494990e-01;
  self->a[4][2]  = 1.0162238957486987e-01;

  self->b[0][1]  = 6.0383216899694780e-01;
  self->b[1][1]  = 6.8140854070765100e-01;
  self->b[1][2]  =-9.4032232364004587e-01;
  self->b[2][1]  = 7.4908140417442326e-01;
  self->b[2][2]  =-8.0788789309839970e-01;
  self->b[3][1]  = 9.1026230884298709e-01;
  self->b[3][2]  =-6.3619282970522140e-01;
  self->b[4][1]  = 1.1094578293400919e+00;
  self->b[4][2]  =-4.5209734630478149e-01;

  return self;

}


// Chebyshev half band filter (halfband-cheby.fdl, Fp 0.38 - Fs 0.50)

IIR* IIR_CreateHalfbandCheby() {

  IIR* self = malloc(sizeof(IIR));
  assert(self != NULL);

  self->numSecondOrderStages = 7;
  self->firstOrderStage      = 0;
  memset(self->w, 0.0, sizeof(self->w));

  self->a[0][0]  = 6.7321035456699241e-01;
  self->a[0][1]  = 4.2796255903323940e-04;
  self->a[0][2]  = 6.7321035456699274e-01;
  self->a[1][0]  = 5.8400736078640558e-01;
  self->a[1][1]  = 6.0405913763782487e-02;
  self->a[1][2]  = 5.8400736078640547e-01;
  self->a[2][0]  = 5.0234705112435063e-01;
  self->a[2][1]  = 1.5977562044402663e-01;
  self->a[2][2]  = 5.0234705112435063e-01;
  self->a[3][0]  = 4.2742912873328470e-01;
  self->a[3][1]  = 2.8039221615182286e-01;
  self->a[3][2]  = 4.2742912873328470e-01;
  self->a[4][0]  = 3.6243768451041292e-01;
  self->a[4][1]  = 4.0204664955809477e-01;
  self->a[4][2]  = 3.6243768451041292e-01;
  self->a[5][0]  = 3.1328878757199902e-01;
  self->a[5][1]  = 5.0198545675408213e-01;
  self->a[5][2]  = 3.1328878757199902e-01;
  self->a[6][0]  = 2.8653355009504189e-01;
  self->a[6][1]  = 5.5870812802157532e-01;
  self->a[6][2]  = 2.8653355009504189e-01;

  self->b[0][1]  = 5.2051845470284408e-01;
  self->b[0][2]  =-8.6736712639586289e-01;
  self->b[1][1]  = 4.1473382711351781e-01;
  self->b[1][2]  =-6.4315446245011143e-01;
  self->b[2][1]  = 2.9062860298232512e-01;
  self->b[2][2]  =-4.5509832567505287e-01;
  self->b[3][1]  = 1.5871031953464074e-01;
  self->b[3][2]  =-2.9396079315303286e-01;
  self->b[4][1]  = 3.3834530303229714e-02;
  self->b[4][2]  =-1.6075654888215035e-01;
  self->b[5][1]  =-6.5469550789326411e-02;
  self->b[5][2]  =-6.3093481108753985e-02;
  self->b[6][1]  =-1.2094977946005982e-01;
  self->b[6][2]  =-1.0825448751599250e-02;

  return self;

}


// Elliptic quarter band (quartband-ellip.fdl)
//  Fp 0.17 - Fs 0.25

IIR* IIR_CreateQuartbandEllip() {

  IIR* self = malloc(sizeof(IIR));
  assert(self != NULL);

  self->numSecondOrderStages = 4;
  self->firstOrderStage      = 1;
  memset(self->w, 0.0, sizeof(self->w));

  self->a[0][0]  = 9.8850523071517926e-02;
  self->a[0][1]  = 9.8850523071517926e-02;
  self->a[1][0]  = 5.5301344066046088e-01;
  self->a[1][1]  =-8.1889355015645460e-01;
  self->a[1][2]  = 5.5301344066046088e-01;
  self->a[2][0]  = 3.9427507459238431e-01;
  self->a[2][1]  =-5.4824430698764104e-01;
  self->a[2][2]  = 3.9427507459238431e-01;
  self->a[3][0]  = 1.7942551498469053e-01;
  self->a[3][1]  =-1.9695567003227360e-01;
  self->a[3][2]  = 1.7942551498469050e-01;
  self->a[4][0]  = 4.0339714934714936e-02;
  self->a[4][1]  =-3.1282615298621687e-03;
  self->a[4][2]  = 4.0339714934714936e-02;

  self->b[0][1]  = 8.0229895385696415e-01;
  self->b[1][1]  = 1.6751553362513882e+00;
  self->b[1][2]  =-9.6228866741585539e-01;
  self->b[2][1]  = 1.6399417063748745e+00;
  self->b[2][2]  =-8.8024754857200194e-01;
  self->b[3][1]  = 1.6199758048473503e+00;
  self->b[3][2]  =-7.8187116478445762e-01;
  self->b[4][1]  = 1.6085629988999295e+00;
  self->b[4][2]  =-6.8611416723949725e-01;

  return self;

}


// Chebyshev quarter band (quartband-cheby.fdl)
//  Fp 0.17 - Fs 0.25

IIR* IIR_CreateQuartbandCheby() {

  IIR* self = malloc(sizeof(IIR));
  assert(self != NULL);

  self->numSecondOrderStages = 7;
  self->firstOrderStage      = 0;
  memset(self->w, 0.0, sizeof(self->w));

  self->a[0][0]  = 5.7728871322864739e-01;
  self->a[0][1]  =-8.2391544415341611e-01;
  self->a[0][2]  = 5.7728871322864739e-01;
  self->a[1][0]  = 5.1386229992878518e-01;
  self->a[1][1]  =-7.0648069080209552e-01;
  self->a[1][2]  = 5.1386229992878540e-01;
  self->a[2][0]  = 4.3570132350670182e-01;
  self->a[2][1]  =-5.4529300204476649e-01;
  self->a[2][2]  = 4.3570132350670182e-01;
  self->a[3][0]  = 3.4427602392875833e-01;
  self->a[3][1]  =-3.4681304852514355e-01;
  self->a[3][2]  = 3.4427602392875828e-01;
  self->a[4][0]  = 2.4702924485313801e-01;
  self->a[4][1]  =-1.3013259678576941e-01;
  self->a[4][2]  = 2.4702924485313801e-01;
  self->a[5][0]  = 1.6039991989754324e-01;
  self->a[5][1]  = 6.5476978437827932e-02;
  self->a[5][2]  = 1.6039991989754324e-01;
  self->a[6][0]  = 1.0776074235144498e-01;
  self->a[6][1]  = 1.8509066874200650e-01;
  self->a[6][2]  = 1.0776074235144498e-01;

  self->b[0][1]  = 1.5896616007694404e+00;
  self->b[0][2]  =-9.2032358307331896e-01;
  self->b[1][1]  = 1.4504164979414580e+00;
  self->b[1][2]  =-7.7166040699693306e-01;
  self->b[2][1]  = 1.3004968677273347e+00;
  self->b[2][2]  =-6.2660651269597201e-01;
  self->b[3][1]  = 1.1382113322990606e+00;
  self->b[3][2]  =-4.7995033163143375e-01;
  self->b[4][1]  = 9.7291123089203346e-01;
  self->b[4][2]  =-3.3683712381254000e-01;
  self->b[5][1]  = 8.2906187024024480e-01;
  self->b[5][2]  =-2.1533868847315921e-01;
  self->b[6][1]  = 7.4264591184916307e-01;
  self->b[6][2]  =-1.4325806529405957e-01;

  return self;

}


// Elliptic 3 % band (3perc-ellip.fdl)
//  Fp 0.026 - Fs 0.034

IIR* IIR_CreateThreePercEllip() {

  IIR* self = malloc(sizeof(IIR));
  assert(self != NULL);

  self->numSecondOrderStages = 4;
  self->firstOrderStage      = 1;
  memset(self->w, 0.0, sizeof(self->w));

  self->a[0][0]  = 6.3536264177563107e-01;
  self->a[0][1]  =-1.2638585895936389e+00;
  self->a[0][2]  = 6.3536264177563095e-01;
  self->a[1][0]  = 5.0420273260036652e-01;
  self->a[1][1]  =-1.0022006481672470e+00;
  self->a[1][2]  = 5.0420273260036652e-01;
  self->a[2][0]  = 2.7845609239175217e-01;
  self->a[2][1]  =-5.5214011758004455e-01;
  self->a[2][2]  = 2.7845609239175212e-01;
  self->a[3][0]  = 7.7816009217007015e-02;
  self->a[3][1]  =-1.5283331315959914e-01;
  self->a[3][2]  = 7.7816009217007015e-02;
  self->a[4][0]  = 4.5780600290754253e-03;
  self->a[4][1]  =-7.9634489446160726e-03;
  self->a[4][2]  = 4.5780600290754253e-03;

  self->b[0][1]  = 1.9888031768026495e+00;
  self->b[0][2]  =-9.9570951261710339e-01;
  self->b[1][1]  = 1.9794982965153960e+00;
  self->b[1][2]  =-9.8570311354888207e-01;
  self->b[2][1]  = 1.9671450448964503e+00;
  self->b[2][2]  =-9.7191711209991005e-01;
  self->b[3][1]  = 1.9520700474806740e+00;
  self->b[3][2]  =-9.5486875275508898e-01;
  self->b[4][1]  = 1.9402266100357981e+00;
  self->b[4][2]  =-9.4141928114933293e-01;

  return self;

}


// Elliptic 3 % band (3perc-ellip.fdl)
//  Fp 0.026 - Fs 0.034

IIR* IIR_CreateThreePercCheby() {

  IIR* self = malloc(sizeof(IIR));
  assert(self != NULL);

  self->numSecondOrderStages = 7;
  self->firstOrderStage      = 0;
  memset(self->w, 0.0, sizeof(self->w));

  self->a[0][0]  = 6.3694621411955843e-01;
  self->a[0][1]  =-1.2666513706723574e+00;
  self->a[0][2]  = 6.3694621411955832e-01;
  self->a[1][0]  = 6.1239304307704767e-01;
  self->a[1][1]  =-1.2172583125043719e+00;
  self->a[1][2]  = 6.1239304307704767e-01;
  self->a[2][0]  = 5.6714628026326919e-01;
  self->a[2][1]  =-1.1260889537237611e+00;
  self->a[2][2]  = 5.6714628026326919e-01;
  self->a[3][0]  = 4.9654923039410015e-01;
  self->a[3][1]  =-9.8375973760428881e-01;
  self->a[3][2]  = 4.9654923039410037e-01;
  self->a[4][0]  = 3.9539423358036552e-01;
  self->a[4][1]  =-7.7977255713689575e-01;
  self->a[4][2]  = 3.9539423358036552e-01;
  self->a[5][0]  = 2.6369423222408661e-01;
  self->a[5][1]  =-5.1415760492013562e-01;
  self->a[5][2]  = 2.6369423222408661e-01;
  self->a[6][0]  = 1.2071902998499874e-01;
  self->a[6][1]  =-2.2578641185038278e-01;
  self->a[6][2]  = 1.2071902998499871e-01;
  self->a[7][0]  = 1.9129541927191705e-02;
  self->a[7][1]  =-2.0882276934165507e-02;
  self->a[7][2]  = 1.9129541927191705e-02;

  self->b[0][1]  = 1.9827770553926043e+00;
  self->b[0][2]  =-9.9001811295936348e-01;
  self->b[1][1]  = 1.9617396275092944e+00;
  self->b[1][2]  =-9.6926740115901788e-01;
  self->b[2][1]  = 1.9374087760910630e+00;
  self->b[2][2]  =-9.4561238289384020e-01;
  self->b[3][1]  = 1.9073402329717106e+00;
  self->b[3][2]  =-9.1667895615562212e-01;
  self->b[4][1]  = 1.8692233778084297e+00;
  self->b[4][2]  =-8.8023928783226502e-01;
  self->b[5][1]  = 1.8226623711919956e+00;
  self->b[5][2]  =-8.3589323072003319e-01;
  self->b[6][1]  = 1.7737021856612809e+00;
  self->b[6][2]  =-7.8935383378089552e-01;
  self->b[7][1]  = 1.7394127041907879e+00;
  self->b[7][2]  =-7.5678951111100590e-01;

  return self;

}


// Modified version of the algorithm function designed by FilterDesignLab-IIR
void IIR_filter(IIR* self, float* input, float* output, int length) {

  double y0, w0, w1, w2, x0;
  const int numSecondOrderStages = self->numSecondOrderStages;
  const int firstOrderStage      = self->firstOrderStage;

  /* -------- Filter Algorithm -  Second order Structure, Direct Form 2 ------
   w[0][n] = x[n]            + b[0][1]*w[0][n-1] + b[0][2]*w[0][n-2]
   y[0][n] = a[0][0]*w[0][n] + a[0][1]*w[0][n-1] + a[0][2]*w[0][n-2]
   w[1][n] = y[0][n]         + b[1][1]*w[1][n-1] + b[1][2]*w[1][n-2]
   y[n]    = a[1][0]*w[1][n] + a[1][1]*w[1][n-1] + a[1][2]*w[1][n-2]
   ...
  ------------------------------------------------------------------------- */

  for (int n = 0; n < length; n++) {

    // Cycle buffers
    for (int m = 0; m < numSecondOrderStages+firstOrderStage; ++m) {
      self->w[m][2] = self->w[m][1];
      self->w[m][1] = self->w[m][0];
    }

    // Do first order contribution
    if (firstOrderStage == 1) {
      self->w[0][0] = input[n] + self->b[0][1] * self->w[0][1];
      y0 = self->a[0][0] * self->w[0][0] + self->a[0][1] * self->w[0][1];
    }

    // Second order contributions
    if (numSecondOrderStages > 0) {

      if (firstOrderStage == 0) {
        y0 = input[n];
      }

      for (int m = 0; m < numSecondOrderStages; ++m) {
        x0 = y0;

        w2 = self->w[m+firstOrderStage][2];
        w1 = self->w[m+firstOrderStage][1];

        w0 = self->w[m+firstOrderStage][0]
           = x0 + self->b[m+firstOrderStage][1] * w1
                + self->b[m+firstOrderStage][2] * w2;

        y0 = self->a[m+firstOrderStage][0] * w0 +
             self->a[m+firstOrderStage][1] * w1 +
             self->a[m+firstOrderStage][2] * w2;
      }

    }

    output[n] = y0;
  }

}


void IIR_reset(IIR* self) {
  memset(self->w, 0.0, sizeof(self->w));
}