/* biquad.c generated by valac 0.18.1, the Vala compiler
 * generated from biquad.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define TYPE_BIQUAD (biquad_get_type ())
#define BIQUAD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BIQUAD, Biquad))
#define BIQUAD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BIQUAD, BiquadClass))
#define IS_BIQUAD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BIQUAD))
#define IS_BIQUAD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BIQUAD))
#define BIQUAD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BIQUAD, BiquadClass))

typedef struct _Biquad Biquad;
typedef struct _BiquadClass BiquadClass;
typedef struct _BiquadPrivate BiquadPrivate;
typedef struct _ParamSpecBiquad ParamSpecBiquad;

struct _Biquad {
	GTypeInstance parent_instance;
	volatile int ref_count;
	BiquadPrivate * priv;
};

struct _BiquadClass {
	GTypeClass parent_class;
	void (*finalize) (Biquad *self);
};

struct _BiquadPrivate {
	gdouble* z1;
	gint z1_length1;
	gint _z1_size_;
	gdouble* z2;
	gint z2_length1;
	gint _z2_size_;
};

struct _ParamSpecBiquad {
	GParamSpec parent_instance;
};


static gpointer biquad_parent_class = NULL;

gpointer biquad_ref (gpointer instance);
void biquad_unref (gpointer instance);
GParamSpec* param_spec_biquad (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_biquad (GValue* value, gpointer v_object);
void value_take_biquad (GValue* value, gpointer v_object);
gpointer value_get_biquad (const GValue* value);
GType biquad_get_type (void) G_GNUC_CONST;
#define BIQUAD_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_BIQUAD, BiquadPrivate))
enum  {
	BIQUAD_DUMMY_PROPERTY
};
Biquad* biquad_new (gint sectionCount);
Biquad* biquad_construct (GType object_type, gint sectionCount);
gdouble* biquad_lowpass (gdouble cutoff, gdouble samplerate, gdouble Q, int* result_length1);
gdouble* biquad_highpass (gdouble cutoff, gdouble samplerate, gdouble Q, int* result_length1);
gdouble* biquad_bandpass (gdouble cutoff, gdouble samplerate, gdouble Q, int* result_length1);
void biquad_reset (Biquad* self);
void biquad_filter (Biquad* self, gdouble* biquad, int biquad_length1, gfloat* input, int input_length1, gfloat* output, int output_length1);
static void biquad_finalize (Biquad* obj);


Biquad* biquad_construct (GType object_type, gint sectionCount) {
	Biquad* self = NULL;
	gint _tmp0_;
	gdouble* _tmp1_ = NULL;
	gint _tmp2_;
	gdouble* _tmp3_ = NULL;
	self = (Biquad*) g_type_create_instance (object_type);
	_tmp0_ = sectionCount;
	_tmp1_ = g_new0 (gdouble, _tmp0_);
	self->priv->z1 = (g_free (self->priv->z1), NULL);
	self->priv->z1 = _tmp1_;
	self->priv->z1_length1 = _tmp0_;
	self->priv->_z1_size_ = self->priv->z1_length1;
	_tmp2_ = sectionCount;
	_tmp3_ = g_new0 (gdouble, _tmp2_);
	self->priv->z2 = (g_free (self->priv->z2), NULL);
	self->priv->z2 = _tmp3_;
	self->priv->z2_length1 = _tmp2_;
	self->priv->_z2_size_ = self->priv->z2_length1;
	return self;
}


Biquad* biquad_new (gint sectionCount) {
	return biquad_construct (TYPE_BIQUAD, sectionCount);
}


gdouble* biquad_lowpass (gdouble cutoff, gdouble samplerate, gdouble Q, int* result_length1) {
	gdouble* result = NULL;
	gdouble _tmp0_;
	gdouble _tmp1_;
	gdouble _tmp2_ = 0.0;
	gdouble K;
	gdouble _tmp3_;
	gdouble norm;
	gdouble a0;
	gdouble a1;
	gdouble a2;
	gdouble b1;
	gdouble _tmp4_;
	gdouble b2;
	gdouble* _tmp5_ = NULL;
	gdouble* _tmp6_;
	gint _tmp6__length1;
	_tmp0_ = cutoff;
	_tmp1_ = samplerate;
	_tmp2_ = tan ((G_PI * _tmp0_) / _tmp1_);
	K = _tmp2_;
	_tmp3_ = Q;
	norm = 1 / ((1 + (K / _tmp3_)) + (K * K));
	a0 = (K * K) * norm;
	a1 = 2 * a0;
	a2 = a0;
	b1 = (2 * ((K * K) - 1)) * norm;
	_tmp4_ = Q;
	b2 = ((1 - (K / _tmp4_)) + (K * K)) * norm;
	_tmp5_ = g_new0 (gdouble, 5);
	_tmp5_[0] = a0;
	_tmp5_[1] = a1;
	_tmp5_[2] = a2;
	_tmp5_[3] = b1;
	_tmp5_[4] = b2;
	_tmp6_ = _tmp5_;
	_tmp6__length1 = 5;
	if (result_length1) {
		*result_length1 = _tmp6__length1;
	}
	result = _tmp6_;
	return result;
}


gdouble* biquad_highpass (gdouble cutoff, gdouble samplerate, gdouble Q, int* result_length1) {
	gdouble* result = NULL;
	gdouble _tmp0_;
	gdouble _tmp1_;
	gdouble _tmp2_ = 0.0;
	gdouble K;
	gdouble _tmp3_;
	gdouble norm;
	gdouble a0;
	gdouble a1;
	gdouble a2;
	gdouble b1;
	gdouble _tmp4_;
	gdouble b2;
	gdouble* _tmp5_ = NULL;
	gdouble* _tmp6_;
	gint _tmp6__length1;
	_tmp0_ = cutoff;
	_tmp1_ = samplerate;
	_tmp2_ = tan ((G_PI * _tmp0_) / _tmp1_);
	K = _tmp2_;
	_tmp3_ = Q;
	norm = 1 / ((1 + (K / _tmp3_)) + (K * K));
	a0 = 1 * norm;
	a1 = (-2) * a0;
	a2 = a0;
	b1 = (2 * ((K * K) - 1)) * norm;
	_tmp4_ = Q;
	b2 = ((1 - (K / _tmp4_)) + (K * K)) * norm;
	_tmp5_ = g_new0 (gdouble, 5);
	_tmp5_[0] = a0;
	_tmp5_[1] = a1;
	_tmp5_[2] = a2;
	_tmp5_[3] = b1;
	_tmp5_[4] = b2;
	_tmp6_ = _tmp5_;
	_tmp6__length1 = 5;
	if (result_length1) {
		*result_length1 = _tmp6__length1;
	}
	result = _tmp6_;
	return result;
}


gdouble* biquad_bandpass (gdouble cutoff, gdouble samplerate, gdouble Q, int* result_length1) {
	gdouble* result = NULL;
	gdouble _tmp0_;
	gdouble _tmp1_;
	gdouble _tmp2_ = 0.0;
	gdouble K;
	gdouble _tmp3_;
	gdouble norm;
	gdouble _tmp4_;
	gdouble a0;
	gint a1;
	gdouble a2;
	gdouble b1;
	gdouble _tmp5_;
	gdouble b2;
	gdouble* _tmp6_ = NULL;
	gdouble* _tmp7_;
	gint _tmp7__length1;
	_tmp0_ = cutoff;
	_tmp1_ = samplerate;
	_tmp2_ = tan ((G_PI * _tmp0_) / _tmp1_);
	K = _tmp2_;
	_tmp3_ = Q;
	norm = 1 / ((1 + (K / _tmp3_)) + (K * K));
	_tmp4_ = Q;
	a0 = (K / _tmp4_) * norm;
	a1 = 0;
	a2 = -a0;
	b1 = (2 * ((K * K) - 1)) * norm;
	_tmp5_ = Q;
	b2 = ((1 - (K / _tmp5_)) + (K * K)) * norm;
	_tmp6_ = g_new0 (gdouble, 5);
	_tmp6_[0] = a0;
	_tmp6_[1] = (gdouble) a1;
	_tmp6_[2] = a2;
	_tmp6_[3] = b1;
	_tmp6_[4] = b2;
	_tmp7_ = _tmp6_;
	_tmp7__length1 = 5;
	if (result_length1) {
		*result_length1 = _tmp7__length1;
	}
	result = _tmp7_;
	return result;
}


void biquad_reset (Biquad* self) {
	g_return_if_fail (self != NULL);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_;
				gint _tmp3_;
				gdouble* _tmp4_;
				gint _tmp4__length1;
				gdouble* _tmp5_;
				gint _tmp5__length1;
				gint _tmp6_;
				gdouble _tmp7_;
				gdouble* _tmp8_;
				gint _tmp8__length1;
				gint _tmp9_;
				gdouble _tmp10_;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = self->priv->z1;
				_tmp4__length1 = self->priv->z1_length1;
				if (!(_tmp3_ < _tmp4__length1)) {
					break;
				}
				_tmp5_ = self->priv->z1;
				_tmp5__length1 = self->priv->z1_length1;
				_tmp6_ = i;
				_tmp5_[_tmp6_] = 0.0;
				_tmp7_ = _tmp5_[_tmp6_];
				_tmp8_ = self->priv->z2;
				_tmp8__length1 = self->priv->z2_length1;
				_tmp9_ = i;
				_tmp8_[_tmp9_] = 0.0;
				_tmp10_ = _tmp8_[_tmp9_];
			}
		}
	}
}


void biquad_filter (Biquad* self, gdouble* biquad, int biquad_length1, gfloat* input, int input_length1, gfloat* output, int output_length1) {
	gdouble* _tmp0_;
	gint _tmp0__length1;
	gdouble y;
	gdouble x;
	g_return_if_fail (self != NULL);
	_tmp0_ = biquad;
	_tmp0__length1 = biquad_length1;
	if (_tmp0__length1 < 5) {
		return;
	}
	y = 0.0;
	x = 0.0;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				gboolean _tmp2_;
				gint _tmp4_;
				gfloat* _tmp5_;
				gint _tmp5__length1;
				gfloat* _tmp6_;
				gint _tmp6__length1;
				gint _tmp7_;
				gfloat _tmp8_;
				gfloat* _tmp42_;
				gint _tmp42__length1;
				gint _tmp43_;
				gdouble _tmp44_;
				gfloat _tmp45_;
				_tmp2_ = _tmp1_;
				if (!_tmp2_) {
					gint _tmp3_;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = input;
				_tmp5__length1 = input_length1;
				if (!(_tmp4_ < _tmp5__length1)) {
					break;
				}
				_tmp6_ = input;
				_tmp6__length1 = input_length1;
				_tmp7_ = i;
				_tmp8_ = _tmp6_[_tmp7_];
				x = (gdouble) _tmp8_;
				{
					gint j;
					j = 0;
					{
						gboolean _tmp9_;
						_tmp9_ = TRUE;
						while (TRUE) {
							gboolean _tmp10_;
							gint _tmp12_;
							gdouble* _tmp13_;
							gint _tmp13__length1;
							gdouble _tmp14_;
							gdouble* _tmp15_;
							gint _tmp15__length1;
							gdouble _tmp16_;
							gdouble* _tmp17_;
							gint _tmp17__length1;
							gint _tmp18_;
							gdouble _tmp19_;
							gdouble* _tmp20_;
							gint _tmp20__length1;
							gint _tmp21_;
							gdouble _tmp22_;
							gdouble* _tmp23_;
							gint _tmp23__length1;
							gdouble _tmp24_;
							gdouble* _tmp25_;
							gint _tmp25__length1;
							gint _tmp26_;
							gdouble _tmp27_;
							gdouble* _tmp28_;
							gint _tmp28__length1;
							gdouble _tmp29_;
							gdouble _tmp30_;
							gdouble _tmp31_;
							gdouble* _tmp32_;
							gint _tmp32__length1;
							gint _tmp33_;
							gdouble _tmp34_;
							gdouble* _tmp35_;
							gint _tmp35__length1;
							gdouble _tmp36_;
							gdouble* _tmp37_;
							gint _tmp37__length1;
							gdouble _tmp38_;
							gdouble _tmp39_;
							gdouble _tmp40_;
							gdouble _tmp41_;
							_tmp10_ = _tmp9_;
							if (!_tmp10_) {
								gint _tmp11_;
								_tmp11_ = j;
								j = _tmp11_ + 1;
							}
							_tmp9_ = FALSE;
							_tmp12_ = j;
							_tmp13_ = self->priv->z1;
							_tmp13__length1 = self->priv->z1_length1;
							if (!(_tmp12_ < _tmp13__length1)) {
								break;
							}
							_tmp14_ = x;
							_tmp15_ = biquad;
							_tmp15__length1 = biquad_length1;
							_tmp16_ = _tmp15_[0];
							_tmp17_ = self->priv->z1;
							_tmp17__length1 = self->priv->z1_length1;
							_tmp18_ = j;
							_tmp19_ = _tmp17_[_tmp18_];
							y = (_tmp14_ * _tmp16_) + _tmp19_;
							_tmp20_ = self->priv->z1;
							_tmp20__length1 = self->priv->z1_length1;
							_tmp21_ = j;
							_tmp22_ = x;
							_tmp23_ = biquad;
							_tmp23__length1 = biquad_length1;
							_tmp24_ = _tmp23_[1];
							_tmp25_ = self->priv->z2;
							_tmp25__length1 = self->priv->z2_length1;
							_tmp26_ = j;
							_tmp27_ = _tmp25_[_tmp26_];
							_tmp28_ = biquad;
							_tmp28__length1 = biquad_length1;
							_tmp29_ = _tmp28_[3];
							_tmp30_ = y;
							_tmp20_[_tmp21_] = ((_tmp22_ * _tmp24_) + _tmp27_) - (_tmp29_ * _tmp30_);
							_tmp31_ = _tmp20_[_tmp21_];
							_tmp32_ = self->priv->z2;
							_tmp32__length1 = self->priv->z2_length1;
							_tmp33_ = j;
							_tmp34_ = x;
							_tmp35_ = biquad;
							_tmp35__length1 = biquad_length1;
							_tmp36_ = _tmp35_[2];
							_tmp37_ = biquad;
							_tmp37__length1 = biquad_length1;
							_tmp38_ = _tmp37_[4];
							_tmp39_ = y;
							_tmp32_[_tmp33_] = (_tmp34_ * _tmp36_) - (_tmp38_ * _tmp39_);
							_tmp40_ = _tmp32_[_tmp33_];
							_tmp41_ = y;
							x = _tmp41_;
						}
					}
				}
				_tmp42_ = output;
				_tmp42__length1 = output_length1;
				_tmp43_ = i;
				_tmp44_ = y;
				_tmp42_[_tmp43_] = (gfloat) _tmp44_;
				_tmp45_ = _tmp42_[_tmp43_];
			}
		}
	}
}


static void value_biquad_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_biquad_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		biquad_unref (value->data[0].v_pointer);
	}
}


static void value_biquad_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = biquad_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_biquad_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_biquad_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		Biquad* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = biquad_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_biquad_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Biquad** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = biquad_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_biquad (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecBiquad* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_BIQUAD), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_biquad (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_BIQUAD), NULL);
	return value->data[0].v_pointer;
}


void value_set_biquad (GValue* value, gpointer v_object) {
	Biquad* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_BIQUAD));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_BIQUAD));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		biquad_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		biquad_unref (old);
	}
}


void value_take_biquad (GValue* value, gpointer v_object) {
	Biquad* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_BIQUAD));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_BIQUAD));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		biquad_unref (old);
	}
}


static void biquad_class_init (BiquadClass * klass) {
	biquad_parent_class = g_type_class_peek_parent (klass);
	BIQUAD_CLASS (klass)->finalize = biquad_finalize;
	g_type_class_add_private (klass, sizeof (BiquadPrivate));
}


static void biquad_instance_init (Biquad * self) {
	self->priv = BIQUAD_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void biquad_finalize (Biquad* obj) {
	Biquad * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_BIQUAD, Biquad);
	self->priv->z1 = (g_free (self->priv->z1), NULL);
	self->priv->z2 = (g_free (self->priv->z2), NULL);
}


/**
 *  IIR Biquad filter
 *
 *  Biquad formulas from:
 *    Nigel Redmon
 *    http://www.earlevel.com/main/2011/01/02/biquad-formulas/
 */
GType biquad_get_type (void) {
	static volatile gsize biquad_type_id__volatile = 0;
	if (g_once_init_enter (&biquad_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_biquad_init, value_biquad_free_value, value_biquad_copy_value, value_biquad_peek_pointer, "p", value_biquad_collect_value, "p", value_biquad_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (BiquadClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) biquad_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Biquad), 0, (GInstanceInitFunc) biquad_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType biquad_type_id;
		biquad_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Biquad", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&biquad_type_id__volatile, biquad_type_id);
	}
	return biquad_type_id__volatile;
}


gpointer biquad_ref (gpointer instance) {
	Biquad* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void biquad_unref (gpointer instance) {
	Biquad* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		BIQUAD_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



