/* misc.c generated by valac 0.18.1, the Vala compiler
 * generated from misc.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <string.h>


#define TYPE_RGB (rgb_get_type ())
typedef struct _RGB RGB;

struct _RGB {
	gfloat r;
	gfloat g;
	gfloat b;
};



GType rgb_get_type (void) G_GNUC_CONST;
RGB* rgb_dup (const RGB* self);
void rgb_free (RGB* self);
void rgb_init (RGB *self, gfloat r, gfloat g, gfloat b);


void rgb_init (RGB *self, gfloat r, gfloat g, gfloat b) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	memset (self, 0, sizeof (RGB));
	_tmp0_ = r;
	(*self).r = _tmp0_;
	_tmp1_ = g;
	(*self).g = _tmp1_;
	_tmp2_ = b;
	(*self).b = _tmp2_;
}


RGB* rgb_dup (const RGB* self) {
	RGB* dup;
	dup = g_new0 (RGB, 1);
	memcpy (dup, self, sizeof (RGB));
	return dup;
}


void rgb_free (RGB* self) {
	g_free (self);
}


GType rgb_get_type (void) {
	static volatile gsize rgb_type_id__volatile = 0;
	if (g_once_init_enter (&rgb_type_id__volatile)) {
		GType rgb_type_id;
		rgb_type_id = g_boxed_type_register_static ("RGB", (GBoxedCopyFunc) rgb_dup, (GBoxedFreeFunc) rgb_free);
		g_once_init_leave (&rgb_type_id__volatile, rgb_type_id);
	}
	return rgb_type_id__volatile;
}



