/* tuning.c generated by valac 0.18.1, the Vala compiler
 * generated from tuning.vala, do not modify */

/*
  Copyright (C) 2012 Davorin Šego
*/

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TUNING_TYPE_12_TET (tuning_12_tet_get_type ())
#define TUNING_12_TET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TUNING_TYPE_12_TET, Tuning12TET))
#define TUNING_12_TET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TUNING_TYPE_12_TET, Tuning12TETClass))
#define TUNING_IS_12_TET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TUNING_TYPE_12_TET))
#define TUNING_IS_12_TET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TUNING_TYPE_12_TET))
#define TUNING_12_TET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TUNING_TYPE_12_TET, Tuning12TETClass))

typedef struct _Tuning12TET Tuning12TET;
typedef struct _Tuning12TETClass Tuning12TETClass;
typedef struct _Tuning12TETPrivate Tuning12TETPrivate;

#define TUNING_12_TET_TYPE_NOTE (tuning_12_tet_note_get_type ())
typedef struct _Tuning12TETNote Tuning12TETNote;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _TuningParamSpec12TET TuningParamSpec12TET;

struct _Tuning12TET {
	GTypeInstance parent_instance;
	volatile int ref_count;
	Tuning12TETPrivate * priv;
};

struct _Tuning12TETClass {
	GTypeClass parent_class;
	void (*finalize) (Tuning12TET *self);
};

struct _Tuning12TETNote {
	gchar* letter;
	gchar* sign;
	gchar* alt_letter;
	gchar* alt_sign;
	gint octave;
	gfloat cents;
	gfloat frequency;
};

struct _TuningParamSpec12TET {
	GParamSpec parent_instance;
};


static gpointer tuning_12_tet_parent_class = NULL;

gpointer tuning_12_tet_ref (gpointer instance);
void tuning_12_tet_unref (gpointer instance);
GParamSpec* tuning_param_spec_12_tet (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tuning_value_set_12_tet (GValue* value, gpointer v_object);
void tuning_value_take_12_tet (GValue* value, gpointer v_object);
gpointer tuning_value_get_12_tet (const GValue* value);
GType tuning_12_tet_get_type (void) G_GNUC_CONST;
enum  {
	TUNING_12_TET_DUMMY_PROPERTY
};
GType tuning_12_tet_note_get_type (void) G_GNUC_CONST;
Tuning12TETNote* tuning_12_tet_note_dup (const Tuning12TETNote* self);
void tuning_12_tet_note_free (Tuning12TETNote* self);
void tuning_12_tet_note_copy (const Tuning12TETNote* self, Tuning12TETNote* dest);
void tuning_12_tet_note_destroy (Tuning12TETNote* self);
void tuning_12_tet_find (gfloat freq, gfloat pitch_standard, gfloat cents_offset, gint transpose, Tuning12TETNote* result);
gfloat tuning_12_tet_freq_to_cents (gfloat freq, gfloat pitch_standard);
void tuning_12_tet_cents_to_note (gfloat cents, gfloat pitch_standard, gfloat cents_offset, gint transpose, Tuning12TETNote* result);
gfloat tuning_12_tet_cents_to_freq (gfloat cents, gfloat pitch_standard);
void tuning_12_tet_find_nearest (gfloat freq, gfloat* notes, int notes_length1, gfloat pitch_standard, Tuning12TETNote* result);
Tuning12TET* tuning_12_tet_new (void);
Tuning12TET* tuning_12_tet_construct (GType object_type);
static void tuning_12_tet_finalize (Tuning12TET* obj);


void tuning_12_tet_find (gfloat freq, gfloat pitch_standard, gfloat cents_offset, gint transpose, Tuning12TETNote* result) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_ = 0.0F;
	gfloat cents;
	gfloat _tmp3_;
	gfloat _tmp4_;
	gint _tmp5_;
	Tuning12TETNote _tmp6_ = {0};
	_tmp0_ = freq;
	_tmp1_ = pitch_standard;
	_tmp2_ = tuning_12_tet_freq_to_cents (_tmp0_, _tmp1_);
	cents = _tmp2_;
	_tmp3_ = pitch_standard;
	_tmp4_ = cents_offset;
	_tmp5_ = transpose;
	tuning_12_tet_cents_to_note (cents, _tmp3_, _tmp4_, _tmp5_, &_tmp6_);
	*result = _tmp6_;
	return;
}


gfloat tuning_12_tet_freq_to_cents (gfloat freq, gfloat pitch_standard) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	gfloat _tmp1_;
	gdouble _tmp2_ = 0.0;
	_tmp0_ = freq;
	_tmp1_ = pitch_standard;
	_tmp2_ = log2 ((gdouble) (_tmp0_ / _tmp1_));
	result = (gfloat) (1200.0f * _tmp2_);
	return result;
}


gfloat tuning_12_tet_cents_to_freq (gfloat cents, gfloat pitch_standard) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	gfloat _tmp1_;
	gdouble _tmp2_ = 0.0;
	_tmp0_ = pitch_standard;
	_tmp1_ = cents;
	_tmp2_ = pow (2.0, (gdouble) (_tmp1_ / 1200.0f));
	result = (gfloat) (_tmp0_ * _tmp2_);
	return result;
}


void tuning_12_tet_cents_to_note (gfloat cents, gfloat pitch_standard, gfloat cents_offset, gint transpose, Tuning12TETNote* result) {
	gfloat _tmp0_;
	gdouble _tmp1_ = 0.0;
	gint nearest;
	gint _tmp2_;
	gint _tmp3_;
	gint transposed;
	gint _tmp4_;
	gint octave;
	Tuning12TETNote note = {0};
	gint _tmp5_;
	gint _tmp6_;
	gfloat _tmp7_;
	Tuning12TETNote _tmp8_;
	gfloat _tmp9_;
	gfloat _tmp10_;
	gfloat _tmp11_ = 0.0F;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gint _tmp14_;
	_tmp0_ = cents;
	_tmp1_ = round (_tmp0_ / 100.0);
	nearest = (gint) _tmp1_;
	_tmp2_ = nearest;
	_tmp3_ = transpose;
	transposed = _tmp2_ + _tmp3_;
	_tmp4_ = transposed;
	octave = (gint) ((_tmp4_ / 12.0) + 4.75);
	memset (&note, 0, sizeof (Tuning12TETNote));
	_tmp5_ = octave;
	note.octave = _tmp5_;
	_tmp6_ = nearest;
	_tmp7_ = cents_offset;
	note.cents = (_tmp6_ * 100.f) + _tmp7_;
	_tmp8_ = note;
	_tmp9_ = _tmp8_.cents;
	_tmp10_ = pitch_standard;
	_tmp11_ = tuning_12_tet_cents_to_freq (_tmp9_, _tmp10_);
	note.frequency = _tmp11_;
	_tmp12_ = g_strdup ("");
	_g_free0 (note.sign);
	note.sign = _tmp12_;
	_tmp13_ = g_strdup ("");
	_g_free0 (note.alt_sign);
	note.alt_sign = _tmp13_;
	_tmp14_ = transposed;
	switch (_tmp14_ % 12) {
		case 0:
		{
			gchar* _tmp15_;
			gchar* _tmp16_;
			_tmp15_ = g_strdup ("A");
			_g_free0 (note.letter);
			note.letter = _tmp15_;
			_tmp16_ = g_strdup ("A");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp16_;
			break;
		}
		case 1:
		case -11:
		{
			gchar* _tmp17_;
			gchar* _tmp18_;
			gchar* _tmp19_;
			gchar* _tmp20_;
			_tmp17_ = g_strdup ("A");
			_g_free0 (note.letter);
			note.letter = _tmp17_;
			_tmp18_ = g_strdup ("♯");
			_g_free0 (note.sign);
			note.sign = _tmp18_;
			_tmp19_ = g_strdup ("B");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp19_;
			_tmp20_ = g_strdup ("♭");
			_g_free0 (note.alt_sign);
			note.alt_sign = _tmp20_;
			break;
		}
		case 2:
		case -10:
		{
			gchar* _tmp21_;
			gchar* _tmp22_;
			_tmp21_ = g_strdup ("B");
			_g_free0 (note.letter);
			note.letter = _tmp21_;
			_tmp22_ = g_strdup ("B");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp22_;
			break;
		}
		case 3:
		case -9:
		{
			gchar* _tmp23_;
			gchar* _tmp24_;
			_tmp23_ = g_strdup ("C");
			_g_free0 (note.letter);
			note.letter = _tmp23_;
			_tmp24_ = g_strdup ("C");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp24_;
			break;
		}
		case 4:
		case -8:
		{
			gchar* _tmp25_;
			gchar* _tmp26_;
			gchar* _tmp27_;
			gchar* _tmp28_;
			_tmp25_ = g_strdup ("C");
			_g_free0 (note.letter);
			note.letter = _tmp25_;
			_tmp26_ = g_strdup ("♯");
			_g_free0 (note.sign);
			note.sign = _tmp26_;
			_tmp27_ = g_strdup ("D");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp27_;
			_tmp28_ = g_strdup ("♭");
			_g_free0 (note.alt_sign);
			note.alt_sign = _tmp28_;
			break;
		}
		case 5:
		case -7:
		{
			gchar* _tmp29_;
			gchar* _tmp30_;
			_tmp29_ = g_strdup ("D");
			_g_free0 (note.letter);
			note.letter = _tmp29_;
			_tmp30_ = g_strdup ("D");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp30_;
			break;
		}
		case 6:
		case -6:
		{
			gchar* _tmp31_;
			gchar* _tmp32_;
			gchar* _tmp33_;
			gchar* _tmp34_;
			_tmp31_ = g_strdup ("D");
			_g_free0 (note.letter);
			note.letter = _tmp31_;
			_tmp32_ = g_strdup ("♯");
			_g_free0 (note.sign);
			note.sign = _tmp32_;
			_tmp33_ = g_strdup ("E");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp33_;
			_tmp34_ = g_strdup ("♭");
			_g_free0 (note.alt_sign);
			note.alt_sign = _tmp34_;
			break;
		}
		case 7:
		case -5:
		{
			gchar* _tmp35_;
			gchar* _tmp36_;
			_tmp35_ = g_strdup ("E");
			_g_free0 (note.letter);
			note.letter = _tmp35_;
			_tmp36_ = g_strdup ("E");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp36_;
			break;
		}
		case 8:
		case -4:
		{
			gchar* _tmp37_;
			gchar* _tmp38_;
			_tmp37_ = g_strdup ("F");
			_g_free0 (note.letter);
			note.letter = _tmp37_;
			_tmp38_ = g_strdup ("F");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp38_;
			break;
		}
		case 9:
		case -3:
		{
			gchar* _tmp39_;
			gchar* _tmp40_;
			gchar* _tmp41_;
			gchar* _tmp42_;
			_tmp39_ = g_strdup ("F");
			_g_free0 (note.letter);
			note.letter = _tmp39_;
			_tmp40_ = g_strdup ("♯");
			_g_free0 (note.sign);
			note.sign = _tmp40_;
			_tmp41_ = g_strdup ("G");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp41_;
			_tmp42_ = g_strdup ("♭");
			_g_free0 (note.alt_sign);
			note.alt_sign = _tmp42_;
			break;
		}
		case 10:
		case -2:
		{
			gchar* _tmp43_;
			gchar* _tmp44_;
			_tmp43_ = g_strdup ("G");
			_g_free0 (note.letter);
			note.letter = _tmp43_;
			_tmp44_ = g_strdup ("G");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp44_;
			break;
		}
		case 11:
		case -1:
		{
			gchar* _tmp45_;
			gchar* _tmp46_;
			gchar* _tmp47_;
			gchar* _tmp48_;
			_tmp45_ = g_strdup ("G");
			_g_free0 (note.letter);
			note.letter = _tmp45_;
			_tmp46_ = g_strdup ("♯");
			_g_free0 (note.sign);
			note.sign = _tmp46_;
			_tmp47_ = g_strdup ("A");
			_g_free0 (note.alt_letter);
			note.alt_letter = _tmp47_;
			_tmp48_ = g_strdup ("♭");
			_g_free0 (note.alt_sign);
			note.alt_sign = _tmp48_;
			break;
		}
		default:
		break;
	}
	*result = note;
	return;
}


void tuning_12_tet_find_nearest (gfloat freq, gfloat* notes, int notes_length1, gfloat pitch_standard, Tuning12TETNote* result) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_ = 0.0F;
	gfloat cents;
	gint mid;
	gint low;
	gfloat* _tmp3_;
	gint _tmp3__length1;
	gint high;
	gfloat _tmp15_;
	gfloat _tmp16_ = 0.0F;
	gfloat* _tmp17_;
	gint _tmp17__length1;
	gint _tmp18_;
	gfloat _tmp19_;
	gfloat _tmp20_ = 0.0F;
	gfloat _tmp21_;
	gfloat _tmp22_ = 0.0F;
	gfloat* _tmp23_;
	gint _tmp23__length1;
	gint _tmp24_;
	gfloat _tmp25_;
	gfloat _tmp26_ = 0.0F;
	gfloat _tmp27_;
	gfloat _tmp28_ = 0.0F;
	_tmp0_ = freq;
	_tmp1_ = pitch_standard;
	_tmp2_ = tuning_12_tet_freq_to_cents (_tmp0_, _tmp1_);
	cents = _tmp2_;
	mid = 0;
	low = 0;
	_tmp3_ = notes;
	_tmp3__length1 = notes_length1;
	high = _tmp3__length1 - 1;
	while (TRUE) {
		gint _tmp4_;
		gint _tmp5_;
		gint _tmp6_;
		gint _tmp7_;
		gint _tmp8_;
		gfloat* _tmp9_;
		gint _tmp9__length1;
		gint _tmp10_;
		gfloat _tmp11_;
		gfloat _tmp12_;
		_tmp4_ = high;
		_tmp5_ = low;
		if (!((_tmp4_ - _tmp5_) > 1)) {
			break;
		}
		_tmp6_ = low;
		_tmp7_ = high;
		_tmp8_ = low;
		mid = _tmp6_ + ((_tmp7_ - _tmp8_) / 2);
		_tmp9_ = notes;
		_tmp9__length1 = notes_length1;
		_tmp10_ = mid;
		_tmp11_ = _tmp9_[_tmp10_];
		_tmp12_ = cents;
		if (_tmp11_ >= _tmp12_) {
			gint _tmp13_;
			_tmp13_ = mid;
			high = _tmp13_;
		} else {
			gint _tmp14_;
			_tmp14_ = mid;
			low = _tmp14_;
		}
	}
	_tmp15_ = cents;
	_tmp16_ = fabsf (_tmp15_);
	cents = _tmp16_;
	_tmp17_ = notes;
	_tmp17__length1 = notes_length1;
	_tmp18_ = low;
	_tmp19_ = _tmp17_[_tmp18_];
	_tmp20_ = fabsf (_tmp19_);
	_tmp21_ = cents;
	_tmp22_ = fabsf (_tmp20_ - _tmp21_);
	_tmp23_ = notes;
	_tmp23__length1 = notes_length1;
	_tmp24_ = high;
	_tmp25_ = _tmp23_[_tmp24_];
	_tmp26_ = fabsf (_tmp25_);
	_tmp27_ = cents;
	_tmp28_ = fabsf (_tmp26_ - _tmp27_);
	if (_tmp22_ < _tmp28_) {
		gfloat* _tmp29_;
		gint _tmp29__length1;
		gint _tmp30_;
		gfloat _tmp31_;
		gfloat _tmp32_;
		Tuning12TETNote _tmp33_ = {0};
		_tmp29_ = notes;
		_tmp29__length1 = notes_length1;
		_tmp30_ = low;
		_tmp31_ = _tmp29_[_tmp30_];
		_tmp32_ = pitch_standard;
		tuning_12_tet_cents_to_note (_tmp31_, _tmp32_, 0.f, 0, &_tmp33_);
		*result = _tmp33_;
		return;
	} else {
		gfloat* _tmp34_;
		gint _tmp34__length1;
		gint _tmp35_;
		gfloat _tmp36_;
		gfloat _tmp37_;
		Tuning12TETNote _tmp38_ = {0};
		_tmp34_ = notes;
		_tmp34__length1 = notes_length1;
		_tmp35_ = high;
		_tmp36_ = _tmp34_[_tmp35_];
		_tmp37_ = pitch_standard;
		tuning_12_tet_cents_to_note (_tmp36_, _tmp37_, 0.f, 0, &_tmp38_);
		*result = _tmp38_;
		return;
	}
}


Tuning12TET* tuning_12_tet_construct (GType object_type) {
	Tuning12TET* self = NULL;
	self = (Tuning12TET*) g_type_create_instance (object_type);
	return self;
}


Tuning12TET* tuning_12_tet_new (void) {
	return tuning_12_tet_construct (TUNING_TYPE_12_TET);
}


void tuning_12_tet_note_copy (const Tuning12TETNote* self, Tuning12TETNote* dest) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	gint _tmp8_;
	gfloat _tmp9_;
	gfloat _tmp10_;
	_tmp0_ = (*self).letter;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).letter);
	(*dest).letter = _tmp1_;
	_tmp2_ = (*self).sign;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 ((*dest).sign);
	(*dest).sign = _tmp3_;
	_tmp4_ = (*self).alt_letter;
	_tmp5_ = g_strdup (_tmp4_);
	_g_free0 ((*dest).alt_letter);
	(*dest).alt_letter = _tmp5_;
	_tmp6_ = (*self).alt_sign;
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 ((*dest).alt_sign);
	(*dest).alt_sign = _tmp7_;
	_tmp8_ = (*self).octave;
	(*dest).octave = _tmp8_;
	_tmp9_ = (*self).cents;
	(*dest).cents = _tmp9_;
	_tmp10_ = (*self).frequency;
	(*dest).frequency = _tmp10_;
}


void tuning_12_tet_note_destroy (Tuning12TETNote* self) {
	_g_free0 ((*self).letter);
	_g_free0 ((*self).sign);
	_g_free0 ((*self).alt_letter);
	_g_free0 ((*self).alt_sign);
}


Tuning12TETNote* tuning_12_tet_note_dup (const Tuning12TETNote* self) {
	Tuning12TETNote* dup;
	dup = g_new0 (Tuning12TETNote, 1);
	tuning_12_tet_note_copy (self, dup);
	return dup;
}


void tuning_12_tet_note_free (Tuning12TETNote* self) {
	tuning_12_tet_note_destroy (self);
	g_free (self);
}


GType tuning_12_tet_note_get_type (void) {
	static volatile gsize tuning_12_tet_note_type_id__volatile = 0;
	if (g_once_init_enter (&tuning_12_tet_note_type_id__volatile)) {
		GType tuning_12_tet_note_type_id;
		tuning_12_tet_note_type_id = g_boxed_type_register_static ("Tuning12TETNote", (GBoxedCopyFunc) tuning_12_tet_note_dup, (GBoxedFreeFunc) tuning_12_tet_note_free);
		g_once_init_leave (&tuning_12_tet_note_type_id__volatile, tuning_12_tet_note_type_id);
	}
	return tuning_12_tet_note_type_id__volatile;
}


static void tuning_value_12_tet_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void tuning_value_12_tet_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		tuning_12_tet_unref (value->data[0].v_pointer);
	}
}


static void tuning_value_12_tet_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = tuning_12_tet_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer tuning_value_12_tet_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* tuning_value_12_tet_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		Tuning12TET* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = tuning_12_tet_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* tuning_value_12_tet_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Tuning12TET** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = tuning_12_tet_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* tuning_param_spec_12_tet (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	TuningParamSpec12TET* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TUNING_TYPE_12_TET), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer tuning_value_get_12_tet (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TUNING_TYPE_12_TET), NULL);
	return value->data[0].v_pointer;
}


void tuning_value_set_12_tet (GValue* value, gpointer v_object) {
	Tuning12TET* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TUNING_TYPE_12_TET));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TUNING_TYPE_12_TET));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		tuning_12_tet_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		tuning_12_tet_unref (old);
	}
}


void tuning_value_take_12_tet (GValue* value, gpointer v_object) {
	Tuning12TET* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TUNING_TYPE_12_TET));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TUNING_TYPE_12_TET));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		tuning_12_tet_unref (old);
	}
}


static void tuning_12_tet_class_init (Tuning12TETClass * klass) {
	tuning_12_tet_parent_class = g_type_class_peek_parent (klass);
	TUNING_12_TET_CLASS (klass)->finalize = tuning_12_tet_finalize;
}


static void tuning_12_tet_instance_init (Tuning12TET * self) {
	self->ref_count = 1;
}


static void tuning_12_tet_finalize (Tuning12TET* obj) {
	Tuning12TET * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TUNING_TYPE_12_TET, Tuning12TET);
}


GType tuning_12_tet_get_type (void) {
	static volatile gsize tuning_12_tet_type_id__volatile = 0;
	if (g_once_init_enter (&tuning_12_tet_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { tuning_value_12_tet_init, tuning_value_12_tet_free_value, tuning_value_12_tet_copy_value, tuning_value_12_tet_peek_pointer, "p", tuning_value_12_tet_collect_value, "p", tuning_value_12_tet_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (Tuning12TETClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tuning_12_tet_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Tuning12TET), 0, (GInstanceInitFunc) tuning_12_tet_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType tuning_12_tet_type_id;
		tuning_12_tet_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Tuning12TET", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&tuning_12_tet_type_id__volatile, tuning_12_tet_type_id);
	}
	return tuning_12_tet_type_id__volatile;
}


gpointer tuning_12_tet_ref (gpointer instance) {
	Tuning12TET* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void tuning_12_tet_unref (gpointer instance) {
	Tuning12TET* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		TUNING_12_TET_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



